- id: terrascan
  name: terrascan
  description: Runs terrascan on Terraform templates.
  language: script
  entry: hooks/terrascan.sh
  files: \.tf$
  exclude: \.terraform\/.*$
  require_serial: true